name: Demo deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build
        run: |
          npm i
          npm t
          npm run build
          mkdir public
          cp ./index.html ./public
          cp -R ./dist ./public

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          force_orphan: true
